name: Tipo de cambio SBS diario

on:
  schedule:
    - cron: "0 11 * * *"   # 8:00 AM Per√∫
  workflow_dispatch:

jobs:
  run-sbs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run SBS script
        env:
          SBS_TOKEN: ${{ secrets.SBS_TOKEN }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python tc_sbs.py
